version: "3"
services:
  frontend:
    image: omkar5655/frontend-react:v4
    container_name: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - CONTAINER_NAME=http://backend:8080
    depends_on:
      - backend
  backend:
    image: omkar5655/backend-node:v4
    container_name: backend
    environment:
      - PGDATABASE=loizenaidb
      - PGUSER=postgres
      - PGPASS=123
      - PGHOST=postgres
      - PGDIALECT=postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: loizenaidb