apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: backend
          image: omkar5655/backend:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: PGDATABASE
              value: loizenaidb
            - name: PGUSER
              value: postgres
            - name: PGPASS
              value: "123"
            - name: PGHOST
              value: postgres-service
            - name: PGDIALECT
              value: postgres