apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  selector:
    matchLabels:
      component: react
  template:
    metadata:
      labels:
        component: react
    spec:
      containers:
        - name: react
          image: omkar5655/frontend:latest
          stdin: true
          ports:
            - containerPort: 3000
